# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ps = Game.create(platform: 'PlayStation4・5')
ps_mhw = ps.children.create(:platform=>"モンスターハンター：アイスボーン")
ps_gta5 = ps.children.create(:platform=>"Grand Theft Auto V")
ps_ds3 = ps.children.create(:platform=>"DARK SOULS３")
ps_gs = ps.children.create(:platform=>"原神")
ps_ffxiv = ps.children.create(:platform=>"ファイナルファンタジーXIV")
ps_dqx = ps.children.create(:platform=>"ドラゴンクエストX オンライン")
ps_al = ps.children.create(:platform=>"APEX LEGENDS")
ps_fn = ps.children.create(:platform=>"FORTNITE")
ps_codw = ps.children.create(:platform=>"Call of Duty: Warzone")
ps_r6s = ps.children.create(:platform=>"Rainbow Six Siege")
ps_sfv = ps.children.create(:platform=>"ストリートファイターV")
ps_dbd = ps.children.create(:platform=>"Dead by Daylight")
ps_pwpr = ps.children.create(:platform=>"e-BASEBALLパワフルプロ野球2020")
ps_fifa = ps.children.create(:platform=>"FIFA22")
ps_rl = ps.children.create(:platform=>"ロケットリーグ")
ps_is = ps.children.create(:platform=>"いただきストリート ドラゴンクエスト&ファイナルファンタジー")
ps_gts = ps.children.create(:platform=>"グランツーリスモSPORT")
ps_mc = ps.children.create(:platform=>"Minecraft")
ps_ark = ps.children.create(:platform=>"ARK: Survival Evolved")


switch = Game.create(:platform=>"Nintendo Switch")
switch_mhr = switch.children.create(:platform=>"モンスターハンター ライズ")
switch_mds = switch.children.create(:platform=>"Minecraft Dungeons")
switch_br = switch.children.create(:platform=>"ボーダーランズ")
switch_pms = switch.children.create(:platform=>"ポケットモンスターソードシールド")
switch_gs = switch.children.create(:platform=>"'原神")
switch_al = switch.children.create(:platform=>"APEX LEGENDS")
switch_fn = switch.children.create(:platform=>"FORTNITE")
switch_st2 = switch.children.create(:platform=>"スプラトゥーン2")
switch_ow = switch.children.create(:platform=>"オーバーウォッチ")
switch_sbs = switch.children.create(:platform=>"大乱闘スマッシュブラザーズSPECIAL")
switch_pmu = switch.children.create(:platform=>"ポケモン ユナイト")
switch_dbd = switch.children.create(:platform=>"Dead by Daylight")
switch_rn2 = switch.children.create(:platform=>"リトルナイトメア 2")
switch_mst = switch.children.create(:platform=>"マリオ＆ソニックAT東京2020オリンピック")
switch_au = switch.children.create(:platform=>"Among Us")
switch_md = switch.children.create(:platform=>"桃太郎電鉄〜昭和 平成 令和も定番")
switch_mc = switch.children.create(:platform=>"Minecraft")
switch_mc8 = switch.children.create(:platform=>"マリオカート8デラックス")
switch_adm = switch.children.create(:platform=>"あつまれどうぶつの森")


pc = Game.create(:platform=>"PC")
pc_mhw = pc.children.create(:platform=>"モンスターハンター：アイスボーン")
pc_gta5 = pc.children.create(:platform=>"Grand Theft Auto V")
pc_ds3 = pc.children.create(:platform=>"DARK SOULS３")
pc_gs = pc.children.create(:platform=>"原神")
pc_ffxiv = pc.children.create(:platform=>"ファイナルファンタジーXIV")
pc_dqx = pc.children.create(:platform=>"ドラゴンクエストX オンライン")
pc_al = pc.children.create(:platform=>"APEX LEGENDS")
pc_fn = pc.children.create(:platform=>"FORTNITE")
pc_vr = pc.children.create(:platform=>"VALORANT")
pc_r6s = pc.children.create(:platform=>"Rainbow Six Siege")
pc_sfv = pc.children.create(:platform=>"ストリートファイターV")
pc_dbd = pc.children.create(:platform=>"Dead by Daylight")
pc_gbs = pc.children.create(:platform=>"Gang Beasts")
pc_l4d2 = pc.children.create(:platform=>"Left 4 Dead 2")
pc_rl = pc.children.create(:platform=>"ロケットリーグ")
pc_oc2 = pc.children.create(:platform=>"Overcooked!2")
pc_ac = pc.children.create(:platform=>"Assetto Corsa")
pc_mc = pc.children.create(:platform=>"Minecraft")
pc_ark = pc.children.create(:platform=>"ARK: Survival Evolved")
pc_hff = pc.children.create(:platform=>"Human Fall Flat")