class Favorite < ActiveHash::Base
  self.data = [
    { id: 1,  name: '--' },
    { id: 2,  name: 'モンスターハンター：アイスボーン' },
    { id: 3,  name: 'グランド・セフト・オートV' },
    { id: 4,  name: 'DARK SOULS３' },
    { id: 5,  name: '原神' },
    { id: 6,  name: 'ファイナルファンタジーXIV' },
    { id: 7,  name: 'ドラゴンクエストX オンライン' },
    { id: 8,  name: 'APEX LEGENDS' },
    { id: 9,  name: 'FORTNITE' },
    { id: 10,  name: 'Call of Duty: Warzone' },
    { id: 11,  name: 'Rainbow Six Siege' },
    { id: 12,  name: 'ストリートファイターⅤ' },
    { id: 13,  name: 'Dead by Daylight' },
    { id: 14,  name: 'e-BASEBALLパワフルプロ野球2020' },
    { id: 15,  name: 'いただきストリート ドラゴンクエスト&ファイナルファンタジー' },
    { id: 16,  name: 'Minecraft' },
    { id: 17,  name: 'ARK: Survival Evolved' },
    { id: 18,  name: 'その他' },

    { id: 19,  name: 'モンスターハンターライズ' },
    { id: 20,  name: 'Minecraft Dungeons' },
    { id: 21,  name: 'ポケットモンスターソードシールド' },
    { id: 22,  name: '原神' },
    { id: 23,  name: 'APEX LEGENDS' },
    { id: 24,  name: 'FORTNITE' },
    { id: 25,  name: 'スプラトゥーン2' },
    { id: 26,  name: 'オーバーウォッチ' },
    { id: 27,  name: '大乱闘スマッシュブラザーズSPECIAL' },
    { id: 28,  name: 'ポケモン ユナイト' },
    { id: 29,  name: 'Dead by Daylight' },
    { id: 30,  name: 'リトルナイトメア 2' },
    { id: 31,  name: 'Among Us' },
    { id: 32,  name: '桃太郎電鉄〜昭和 平成 令和も定番' },
    { id: 33,  name: 'マリオカート8デラックス' },
    { id: 34,  name: 'Minecraft' },
    { id: 35,  name: 'あつまれどうぶつの森' },
    { id: 36,  name: 'Human Fall Flat' },
    { id: 37,  name: 'その他' },

    { id: 38,  name: 'モンスターハンター：アイスボーン' },
    { id: 39,  name: 'DARK SOULS３' },
    { id: 40,  name: 'Grand Theft Auto V' },
    { id: 41,  name: '原神' },
    { id: 42,  name: 'APEX LEGENDS' },
    { id: 43,  name: 'FORTNITE' },
    { id: 44,  name: 'VALORANT' },
    { id: 45,  name: 'Rainbow Six Siege' },
    { id: 46,  name: 'ストリートファイターⅤ' },
    { id: 47,  name: 'Gang Beasts' },
    { id: 48,  name: 'Dead by Daylight' },
    { id: 49,  name: 'リトルナイトメア 2' },
    { id: 50,  name: 'Left 4 Dead 2' },
    { id: 51,  name: 'FIFA 22' },
    { id: 52,  name: 'Among Us' },
    { id: 53,  name: 'Overcooked!2' },
    { id: 54,  name: 'Ultimate Chicken Horse' },
    { id: 55,  name: 'Minecraft' },
    { id: 56,  name: 'ARK: Survival Evolved' },
    { id: 57,  name: 'Human Fall Flat' },
    { id: 58,  name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :users
end